from .lenet import LeNet
from .minivggnet import MiniVGGNet
from .fchead_net import FCHeadNet
from .shallownet import ShallowNet
from .alexnet import AlexNet
from .minigooglenet import MiniGoogLeNet
from .deepergooglenet import DeeperGoogLeNet
from .resnet import ResNet
from .emotionvggnet import EmotionVGGNet
from .alexagegender import AlexNetAgeGender